# Generated by Django 5.1.15 on 2026-04-25 08:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('lessons', '0002_attendance'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='homework_files/%Y/%m/')),
                ('link', models.URLField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('assign_type', models.CharField(choices=[('group', 'Whole Group'), ('lesson', 'For Lesson'), ('individual', 'Individual Student')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='courses.group')),
                ('individual_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_homeworks', to='students.student')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='lessons.lesson')),
            ],
            options={
                'db_table': 'homework_homework',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('checked', 'Checked'), ('revision', 'Needs Revision'), ('overdue', 'Overdue')], default='not_submitted', max_length=20)),
                ('answer_text', models.TextField(blank=True)),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='homework_answers/%Y/%m/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('teacher_comment', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_homework_statuses', to=settings.AUTH_USER_MODEL)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='homework.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_statuses', to='students.student')),
            ],
            options={
                'db_table': 'homework_status',
                'ordering': ['-homework__created_at'],
                'unique_together': {('homework', 'student')},
            },
        ),
    ]
