# Generated by Django 6.0.4 on 2026-08-21 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_alter_homeworkstatus_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkstatus',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
