# Generated by Django 6.0.4 on 2026-06-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('lesson', 'Lesson Grade'), ('homework', 'Homework Grade'), ('exam', 'Exam Grade'), ('activity', 'Activity Grade'), ('speaking', 'Speaking Grade'), ('vocabulary', 'Vocabulary Grade'), ('test', 'Test Grade'), ('extra_lesson', 'Extra Lesson Grade')], max_length=20),
        ),
    ]
