# Generated by Django 6.0.4 on 2026-08-21 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_alter_grade_grade_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.PositiveSmallIntegerField(help_text='Оценка по школьной шкале 2–5.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
