# Generated by Django 6.0.4 on 2026-08-21 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_grade_scale_2_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
