[build]
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile.celery"

[deploy]
startCommand = "sh -c 'cd backend && celery -A config beat -l warning --loglevel=warning'"
restartPolicyType = "on_failure"
