[build]
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile.celery"

[deploy]
startCommand = "sh -c 'cd backend && celery -A config beat -l warning --scheduler django_celery_beat.schedulers:DatabaseScheduler'"
restartPolicyType = "on_failure"
