# railway.toml
[build]
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile"

[deploy]
startCommand = "sh -c 'python manage.py migrate_schemas --shared && python manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p $PORT config.asgi:application'"
healthcheckPath = "/api/v1/health/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
