# Generated by Codex on 2026-05-12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_add_fixed_salary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffPenalty",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.CharField(max_length=255)),
                ("penalty_date", models.DateField()),
                ("status", models.CharField(choices=[("active", "Active"), ("cancelled", "Cancelled")], default="active", max_length=20)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="staff_penalties", to="institutions.branch")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_staff_penalties", to=settings.AUTH_USER_MODEL)),
                ("staff", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="penalties", to="staff.staff")),
            ],
            options={
                "db_table": "staff_penalty",
                "ordering": ["-penalty_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="staffpenalty",
            index=models.Index(fields=["staff", "penalty_date"], name="staff_penal_staff_i_5c285c_idx"),
        ),
        migrations.AddIndex(
            model_name="staffpenalty",
            index=models.Index(fields=["status", "penalty_date"], name="staff_penal_status_ed1bb7_idx"),
        ),
    ]
