# Generated by Django 6.0.4 on 2026-06-09 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffbonus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTeacherLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('support_teacher', models.ForeignKey(limit_choices_to={'role': 'support_teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='supported_teachers', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_teachers', to='staff.staff')),
            ],
            options={
                'db_table': 'staff_support_teacher_link',
                'unique_together': {('support_teacher', 'teacher')},
            },
        ),
    ]
