# Generated by Django 6.0.4 on 2026-07-04 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_supportteacherlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffbonus',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses', to='staff.staff'),
        ),
    ]
