"""Уроки генерируются один раз при создании группы (90 дней вперёд) и
раньше никогда не пересобирались — ни когда горизонт заканчивался, ни
когда меняли расписание группы. Найдено на проде 2026-08-08: 9 из 36
активных групп в одном филиале уже остались без единого будущего урока,
ещё у двух групп время уроков в календаре не совпадало с настройками
группы (расписание поменяли, календарь остался старым).

Note: GroupFactory.create() goes through Group.save(), which fires the
real post_save signal — every group here already has its initial ~90-day
batch of lessons auto-generated by apps.courses.signals the moment the
factory creates it. Tests build on top of that, they don't need to call
generate_lessons_for_group_sync a second time to get a baseline.
"""
from datetime import timedelta
from decimal import Decimal

import pytest
from django.utils import timezone

from apps.lessons.models import Lesson
from apps.lessons.services import generate_lessons_for_group_sync, resync_lessons_for_group
from tests.factories import BranchFactory, CourseFactory, GroupFactory, StaffFactory

pytestmark = pytest.mark.django_db


def _group_starting(days_ago, schedule):
    branch = BranchFactory()
    teacher = StaffFactory(branch=branch)
    course = CourseFactory()
    return GroupFactory(
        branch=branch,
        teacher=teacher,
        course=course,
        schedule=schedule,
        start_date=timezone.now().date() - timedelta(days=days_ago),
    )


def test_generate_lessons_extends_horizon_when_rerun_with_later_to_date():
    """The mechanism the beat task relies on: calling the generator again
    with a later to_date creates the missing tail without duplicating what
    already exists."""
    group = _group_starting(100, schedule=[{"day": 0, "start": "09:00"}])  # Monday only
    count_after_creation = Lesson.objects.filter(group=group).count()
    assert count_after_creation > 0  # auto-generated by the creation signal

    # Re-running with the same horizon creates nothing new (idempotent).
    created_again = generate_lessons_for_group_sync(group, horizon_days=90)
    assert created_again == 0
    assert Lesson.objects.filter(group=group).count() == count_after_creation

    # Extending the horizon further creates the new tail only.
    created_extended = generate_lessons_for_group_sync(
        group, from_date=timezone.now().date(), horizon_days=180
    )
    assert created_extended > 0
    assert Lesson.objects.filter(group=group).count() == count_after_creation + created_extended


def test_resync_removes_stale_future_scheduled_lessons():
    group = _group_starting(
        10,
        schedule=[
            {"day": 0, "start": "09:00"},
            {"day": 2, "start": "09:00"},
            {"day": 4, "start": "09:00"},
        ],
    )
    future_before = Lesson.objects.filter(
        group=group, datetime__date__gte=timezone.now().date(), status="scheduled"
    )
    assert future_before.count() > 0
    stale_ids = set(future_before.values_list("id", flat=True))

    # Group's schedule changes to a single different day — none of the old
    # generated (Mon/Tue/Thu — slot_weekday() treats day=1..7 as Mon..Sun,
    # day=0 as a legacy alias for Monday) rows match it anymore.
    group.schedule = [{"day": 3, "start": "09:00"}]  # Wednesday only
    resync_lessons_for_group(group)

    remaining_stale = Lesson.objects.filter(id__in=stale_ids)
    assert remaining_stale.count() == 0

    new_lessons = Lesson.objects.filter(group=group, datetime__date__gte=timezone.now().date())
    assert new_lessons.count() > 0
    assert all(lesson.datetime.weekday() == 2 for lesson in new_lessons)  # Wednesday


def test_resync_never_touches_conducted_lessons():
    group = _group_starting(10, schedule=[{"day": 0, "start": "09:00"}])

    conducted = Lesson.objects.filter(group=group).first()
    conducted.status = "conducted"
    conducted.save(update_fields=["status"])

    group.schedule = [{"day": 3, "start": "09:00"}]  # different day entirely
    resync_lessons_for_group(group)

    conducted.refresh_from_db()
    assert conducted.status == "conducted"
    assert Lesson.objects.filter(id=conducted.id).exists()


def test_editing_group_schedule_via_save_triggers_resync():
    """Integration: the pre_save/post_save signal pair in
    apps.courses.signals actually fires resync on a plain .save(), not just
    when resync_lessons_for_group is called directly."""
    group = _group_starting(10, schedule=[{"day": 0, "start": "09:00"}])
    old_lesson_ids = set(
        Lesson.objects.filter(
            group=group, datetime__date__gte=timezone.now().date()
        ).values_list("id", flat=True)
    )
    assert old_lesson_ids

    group.schedule = [{"day": 6, "start": "09:00"}]  # Saturday — was never in the old schedule
    group.save()

    assert Lesson.objects.filter(id__in=old_lesson_ids).count() == 0
    new_lessons = Lesson.objects.filter(group=group, datetime__date__gte=timezone.now().date())
    assert new_lessons.count() > 0
    assert all(lesson.datetime.weekday() == 5 for lesson in new_lessons)  # Saturday


def test_saving_group_without_schedule_change_does_not_resync():
    """A save that doesn't touch schedule shouldn't delete/regenerate
    anything — resync is scoped to actual schedule edits only."""
    group = _group_starting(10, schedule=[{"day": 0, "start": "09:00"}])
    lesson_ids_before = set(Lesson.objects.filter(group=group).values_list("id", flat=True))
    assert lesson_ids_before

    group.monthly_price = Decimal("999999.00")
    group.save()

    lesson_ids_after = set(Lesson.objects.filter(group=group).values_list("id", flat=True))
    assert lesson_ids_before == lesson_ids_after


@pytest.mark.skip(reason="Requires django-tenants PostgreSQL backend (extend_lesson_horizons iterates real tenant schemas).")
def test_extend_lesson_horizons_task_across_tenants():
    """Executable spec for the beat task itself — apps.tenants is stripped
    from INSTALLED_APPS under the SQLite test harness (see
    config/settings/test.py), so the actual multi-schema iteration can't
    run here. The per-group mechanism it relies on is covered by
    test_generate_lessons_extends_horizon_when_rerun_with_later_to_date
    above, which does run for real."""
    from apps.lessons.tasks import extend_lesson_horizons

    group = _group_starting(100, schedule=[{"day": 0, "start": "09:00"}])
    Lesson.objects.filter(group=group, datetime__date__gte=timezone.now().date()).delete()

    extend_lesson_horizons()

    assert Lesson.objects.filter(group=group, datetime__date__gte=timezone.now().date()).exists()
