FROM oven/bun:1
WORKDIR /app

# Install dependencies
COPY package.json bun.lockb ./
RUN NODE_ENV=development bun install --frozen-lockfile

# Copy source and build
COPY . .
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ARG VITE_DEFAULT_TENANT_SCHEMA
ENV VITE_DEFAULT_TENANT_SCHEMA=$VITE_DEFAULT_TENANT_SCHEMA
RUN bun run build

EXPOSE 80
ENV PORT=80
ENV HOST=0.0.0.0

CMD ["bun", "run", "serve.ts"]
