# Generated by Codex on 2026-05-08

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("top_up", "Top Up"),
                    ("charge", "Charge"),
                    ("discount", "Discount"),
                    ("refund", "Refund"),
                    ("expense", "Expense"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="finance.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="balance_before",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AlterField(
            model_name="payment",
            name="balance_after",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="payment",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
