# Generated by Django 6.0.4 on 2026-05-08 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_payments'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments', to='staff.staff'),
        ),
    ]
