# Generated by Django 6.0.4 on 2026-05-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payment_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('top_up', 'Top Up'), ('charge', 'Charge'), ('discount', 'Discount'), ('refund', 'Refund'), ('expense', 'Expense'), ('manual_charge', 'Manual Charge'), ('manual_top_up', 'Manual Top Up')], max_length=20),
        ),
    ]
