# Generated by Django 6.0.4 on 2026-05-26 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_student_transfer'),
        ('finance', '0004_alter_payment_payment_type'),
        ('institutions', '0001_initial'),
        ('lessons', '0004_teacherattendance'),
        ('staff', '0004_staffbonus'),
        ('students', '0003_parentlinkcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['branch'], name='payment_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['group'], name='payment_group_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type', 'created_at'], name='payment_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'payment_type'], name='payment_student_type_idx'),
        ),
    ]
