# Generated by Django 6.0.4 on 2026-07-03 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payment_payment_branch_idx_payment_payment_group_idx_and_more'),
        ('staff', '0005_supportteacherlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='staff.staff'),
        ),
    ]
