# Generated by Django 6.0.4 on 2026-07-04 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_add_teacher_to_payment'),
        ('students', '0005_studentlead_trial_lesson_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='students.student'),
        ),
    ]
