# Generated by Django 6.0.4 on 2026-08-31 10:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_payment_wallet_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='funding_source',
            field=models.CharField(choices=[('main', 'Main balance'), ('bonus', 'Bonus balance')], default='main', max_length=10),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
