# Generated by Django 6.0.4 on 2026-08-29 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_seed_expense_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.expensecategory'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
