# Generated by Django 6.0.4 on 2026-08-29 04:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_backfill_payment_category_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodClose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closed_periods', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_period_close',
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reopened_at__isnull', True)), fields=('month',), name='one_open_close_per_month')],
            },
        ),
    ]
