# Generated by Django 6.0.4 on 2026-08-29 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_periodclose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='periodclose',
            constraint=models.CheckConstraint(condition=models.Q(('month__day', 1)), name='period_close_month_is_first_of_month'),
        ),
    ]
