# Generated by Django 6.0.4 on 2026-06-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('director', 'Director'), ('admin', 'Branch Admin'), ('branch_admin', 'Branch Admin'), ('teacher', 'Teacher'), ('support_teacher', 'Support Teacher'), ('student', 'Student'), ('parent', 'Parent')], max_length=20),
        ),
    ]
