# Generated by Django 6.0.4 on 2026-07-05 17:26

from django.db import migrations, models


def merge_admin_role(apps, schema_editor):
    """Все пользователи с устаревшей ролью 'admin' становятся 'branch_admin'."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="admin").update(role="branch_admin")


def reverse_noop(apps, schema_editor):
    # Обратно не разделяем — 'admin' и 'branch_admin' были дублями.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(merge_admin_role, reverse_noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('director', 'Director'), ('branch_admin', 'Branch Admin'), ('teacher', 'Teacher'), ('support_teacher', 'Support Teacher'), ('student', 'Student'), ('parent', 'Parent')], max_length=20),
        ),
    ]
