# Generated by Django 6.0.4 on 2026-08-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('director', 'Director'), ('branch_admin', 'Branch Admin'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('support_teacher', 'Support Teacher'), ('student', 'Student'), ('parent', 'Parent')], max_length=20),
        ),
    ]
