# Generated by Django 6.0.4 on 2026-05-19 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('institutions', '0001_initial'),
        ('students', '0002_studentlead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_date', models.DateField()),
                ('reason', models.CharField(choices=[('schedule_change', 'Schedule change'), ('level_change', 'Level change'), ('branch_change', 'Branch change'), ('student_request', 'Student request'), ('other', 'Other')], default='other', max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('balance_at_transfer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_monthly_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_monthly_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='institutions.branch')),
                ('from_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='courses.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='students.student')),
                ('to_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='institutions.branch')),
                ('to_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='courses.group')),
            ],
            options={
                'db_table': 'student_transfers',
                'ordering': ['-transfer_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'transfer_date'], name='student_tra_student_125b0f_idx')],
            },
        ),
    ]
