# Generated by Django 6.0.4 on 2026-05-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='meta_access_token',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='institution',
            name='meta_pixel_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
