# Generated by Django 6.0.4 on 2026-05-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_institution_meta_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='sms_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='institution',
            name='sms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='sms_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='institution',
            name='sms_sender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
