# Generated by Django 5.1 on 2026-06-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_institution_sms_email_institution_sms_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="plan",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                    ("enterprise", "Enterprise"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
    ]
