# Generated by Django 5.1 on 2026-06-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_institution_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="plan",
        ),
    ]
