# Generated by Django 6.0.4 on 2026-08-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_remove_institution_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='lead_api_key',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
