# Generated by Django 6.0.4 on 2026-09-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_institution_lead_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='lidpixel_status_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='institution',
            name='lidpixel_status_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
