# Generated by Codex on 2026-05-12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentLead",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=32)),
                ("source", models.CharField(choices=[("walk_in", "Walk-in"), ("phone", "Phone"), ("telegram", "Telegram"), ("instagram", "Instagram"), ("referral", "Referral"), ("other", "Other")], default="walk_in", max_length=20)),
                ("status", models.CharField(choices=[("new", "New"), ("contacted", "Contacted"), ("trial", "Trial lesson"), ("won", "Enrolled"), ("lost", "Lost")], default="new", max_length=20)),
                ("next_follow_up", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="student_leads", to="institutions.branch")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_student_leads", to=settings.AUTH_USER_MODEL)),
                ("interested_course", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="student_leads", to="courses.course")),
            ],
            options={
                "db_table": "students_lead",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="studentlead",
            index=models.Index(fields=["status", "next_follow_up"], name="students_le_status_bc1357_idx"),
        ),
        migrations.AddIndex(
            model_name="studentlead",
            index=models.Index(fields=["phone"], name="students_le_phone_05a6ef_idx"),
        ),
    ]
