# Generated by Django 6.0.4 on 2026-05-26 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('students', '0003_parentlinkcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['branch'], name='student_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['wallet_balance'], name='student_wallet_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['branch', 'status'], name='student_branch_status_idx'),
        ),
    ]
