# Generated by Django 6.0.4 on 2026-05-31 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_student_transfer'),
        ('students', '0004_student_student_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlead',
            name='trial_lesson_attended',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentlead',
            name='trial_lesson_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentlead',
            name='trial_lesson_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_leads', to='courses.group'),
        ),
    ]
