# Generated by Django 6.0.4 on 2026-07-29 03:56

import apps.students.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentlead_trial_lesson_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='file',
            field=models.FileField(storage=apps.students.storage.private_document_storage, upload_to=apps.students.storage.student_document_path),
        ),
    ]
