# Generated by Django 6.0.4 on 2026-08-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentlead_trial_lesson_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlead',
            name='source',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('phone', 'Phone'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('referral', 'Referral'), ('lidpixel', 'LidPixel'), ('other', 'Other')], default='walk_in', max_length=20),
        ),
    ]
