# Generated by Django 6.0.4 on 2026-08-25 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentdocument_file'),
        ('students', '0006_alter_studentlead_source'),
    ]

    operations = [
    ]
