# Generated by Django 6.0.4 on 2026-08-31 10:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_merge_20260825_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
