# Generated by Django 6.0.4 on 2026-09-16 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_bonus_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlead',
            name='converted_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentlead',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
