# Generated by Django 6.0.4 on 2026-09-16 15:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_lead_external_id_converted_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatusDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('status_changed', 'Status changed'), ('sale', 'Sale')], max_length=20)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_deliveries', to='students.studentlead')),
            ],
            options={
                'db_table': 'students_lead_status_delivery',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='students_le_status_5516f2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('event', 'sale')), fields=('lead',), name='uniq_sale_delivery_per_lead')],
            },
        ),
    ]
