# Generated by Django 6.0.3 on 2026-04-25 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'superadmin_super_admin',
            },
        ),
        migrations.CreateModel(
            name='InstitutionNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='tenants.institution')),
            ],
            options={
                'db_table': 'superadmin_institution_notice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('freeze', 'Freeze'), ('unfreeze', 'Unfreeze'), ('archive', 'Archive'), ('notify', 'Notify')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('actor_id', models.CharField(blank=True, max_length=50)),
                ('actor_phone', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_logs', to='tenants.institution')),
            ],
            options={
                'db_table': 'superadmin_institution_action_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', 'created_at'], name='superadmin__institu_eb264b_idx'), models.Index(fields=['action', 'created_at'], name='superadmin__action_53d89c_idx')],
            },
        ),
    ]
