# Generated by Django 6.0.4 on 2026-05-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='EduCRM', max_length=255)),
                ('support_email', models.EmailField(blank=True, default='support@educrm.uz', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='+998 71 200 00 00', max_length=50)),
                ('default_language', models.CharField(default='uz', max_length=10)),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('session_timeout', models.IntegerField(default=30)),
                ('require_2fa', models.BooleanField(default=False)),
                ('strong_password', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'superadmin_platform_settings',
            },
        ),
    ]
