# Generated by Django 5.1 on 2026-06-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0002_platformsettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SuperAdmin",
        ),
    ]
