# Generated by Django 6.0.4 on 2026-07-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_remove_dead_superadmin_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionactionlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('freeze', 'Freeze'), ('unfreeze', 'Unfreeze'), ('archive', 'Archive'), ('notify', 'Notify'), ('branch_create', 'Branch Create'), ('branch_update', 'Branch Update'), ('branch_delete', 'Branch Delete')], max_length=20),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='platform_name',
            field=models.CharField(default='GrowBase', max_length=255),
        ),
    ]
