# Generated by Django 6.0.4 on 2026-08-25 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_alter_institutionactionlog_action'),
        ('superadmin', '0004_alter_platform_name_default'),
    ]

    operations = [
    ]
