/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as TeacherRouteRouteImport } from './routes/teacher/route'
import { Route as SuperadminRouteRouteImport } from './routes/superadmin/route'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as ParentRouteRouteImport } from './routes/parent/route'
import { Route as DirectorRouteRouteImport } from './routes/director/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as ParentIndexRouteImport } from './routes/parent/index'
import { Route as DirectorIndexRouteImport } from './routes/director/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TeacherQuizzesRouteImport } from './routes/teacher/quizzes'
import { Route as TeacherQuizCreateRouteImport } from './routes/teacher/quiz-create'
import { Route as TeacherMessagesRouteImport } from './routes/teacher/messages'
import { Route as TeacherHomeworkRouteImport } from './routes/teacher/homework'
import { Route as TeacherGroupsRouteImport } from './routes/teacher/groups'
import { Route as TeacherGradesRouteImport } from './routes/teacher/grades'
import { Route as TeacherFinanceRouteImport } from './routes/teacher/finance'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher/attendance'
import { Route as SuperadminSettingsRouteImport } from './routes/superadmin/settings'
import { Route as SuperadminLogsRouteImport } from './routes/superadmin/logs'
import { Route as SuperadminAnalyticsRouteImport } from './routes/superadmin/analytics'
import { Route as StudentScheduleRouteImport } from './routes/student/schedule'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentMessagesRouteImport } from './routes/student/messages'
import { Route as StudentHomeworkRouteImport } from './routes/student/homework'
import { Route as StudentGradesRouteImport } from './routes/student/grades'
import { Route as PlayCodeRouteImport } from './routes/play.$code'
import { Route as ParentProfileRouteImport } from './routes/parent/profile'
import { Route as ParentMessagesRouteImport } from './routes/parent/messages'
import { Route as ParentChildrenRouteImport } from './routes/parent/children'
import { Route as DirectorStudentsRouteImport } from './routes/director/students'
import { Route as DirectorStaffRouteImport } from './routes/director/staff'
import { Route as DirectorSettingsRouteImport } from './routes/director/settings'
import { Route as DirectorSalariesRouteImport } from './routes/director/salaries'
import { Route as DirectorPenaltiesRouteImport } from './routes/director/penalties'
import { Route as DirectorNotificationsRouteImport } from './routes/director/notifications'
import { Route as DirectorMessagesRouteImport } from './routes/director/messages'
import { Route as DirectorLeadsRouteImport } from './routes/director/leads'
import { Route as DirectorIntegrationsRouteImport } from './routes/director/integrations'
import { Route as DirectorFinanceRouteImport } from './routes/director/finance'
import { Route as DirectorDailyReportRouteImport } from './routes/director/daily-report'
import { Route as DirectorCoursesRouteImport } from './routes/director/courses'
import { Route as DirectorBranchesRouteImport } from './routes/director/branches'
import { Route as DirectorAuditRouteImport } from './routes/director/audit'
import { Route as DirectorAnalyticsRouteImport } from './routes/director/analytics'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminScheduleRouteImport } from './routes/admin/schedule'
import { Route as AdminQuizzesRouteImport } from './routes/admin/quizzes'
import { Route as AdminQuizCreateRouteImport } from './routes/admin/quiz-create'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminGroupsRouteImport } from './routes/admin/groups'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminDailyReportRouteImport } from './routes/admin/daily-report'
import { Route as AdminControlRouteImport } from './routes/admin/control'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAccountsRouteImport } from './routes/admin/accounts'
import { Route as TeacherQuizSessionSessionIdRouteImport } from './routes/teacher/quiz-session.$sessionId'
import { Route as AdminQuizSessionSessionIdRouteImport } from './routes/admin/quiz-session.$sessionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRouteRoute = TeacherRouteRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRouteRoute = SuperadminRouteRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRouteRoute = ParentRouteRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorRouteRoute = DirectorRouteRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRouteRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRouteRoute,
} as any)
const DirectorIndexRoute = DirectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TeacherQuizzesRoute = TeacherQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherQuizCreateRoute = TeacherQuizCreateRouteImport.update({
  id: '/quiz-create',
  path: '/quiz-create',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherMessagesRoute = TeacherMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherHomeworkRoute = TeacherHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherGroupsRoute = TeacherGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherGradesRoute = TeacherGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherFinanceRoute = TeacherFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const SuperadminSettingsRoute = SuperadminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperadminRouteRoute,
} as any)
const SuperadminLogsRoute = SuperadminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SuperadminRouteRoute,
} as any)
const SuperadminAnalyticsRoute = SuperadminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SuperadminRouteRoute,
} as any)
const StudentScheduleRoute = StudentScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentHomeworkRoute = StudentHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentGradesRoute = StudentGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => StudentRouteRoute,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentProfileRoute = ParentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ParentRouteRoute,
} as any)
const ParentMessagesRoute = ParentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ParentRouteRoute,
} as any)
const ParentChildrenRoute = ParentChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => ParentRouteRoute,
} as any)
const DirectorStudentsRoute = DirectorStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const DirectorStaffRoute = DirectorStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const DirectorSettingsRoute = DirectorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const DirectorSalariesRoute = DirectorSalariesRouteImport.update({
  id: '/salaries',
  path: '/salaries',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const DirectorPenaltiesRoute = DirectorPenaltiesRouteImport.update({
  id: '/penalties',
  path: '/penalties',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const DirectorNotificationsRoute = DirectorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const DirectorMessagesRoute = DirectorMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const DirectorLeadsRoute = DirectorLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const DirectorIntegrationsRoute = DirectorIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const DirectorFinanceRoute = DirectorFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const DirectorDailyReportRoute = DirectorDailyReportRouteImport.update({
  id: '/daily-report',
  path: '/daily-report',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const DirectorCoursesRoute = DirectorCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const DirectorBranchesRoute = DirectorBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const DirectorAuditRoute = DirectorAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const DirectorAnalyticsRoute = DirectorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQuizzesRoute = AdminQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQuizCreateRoute = AdminQuizCreateRouteImport.update({
  id: '/quiz-create',
  path: '/quiz-create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDailyReportRoute = AdminDailyReportRouteImport.update({
  id: '/daily-report',
  path: '/daily-report',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminControlRoute = AdminControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TeacherQuizSessionSessionIdRoute =
  TeacherQuizSessionSessionIdRouteImport.update({
    id: '/quiz-session/$sessionId',
    path: '/quiz-session/$sessionId',
    getParentRoute: () => TeacherRouteRoute,
  } as any)
const AdminQuizSessionSessionIdRoute =
  AdminQuizSessionSessionIdRouteImport.update({
    id: '/quiz-session/$sessionId',
    path: '/quiz-session/$sessionId',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/director': typeof DirectorRouteRouteWithChildren
  '/parent': typeof ParentRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/superadmin': typeof SuperadminRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/apply': typeof ApplyRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/control': typeof AdminControlRoute
  '/admin/daily-report': typeof AdminDailyReportRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/quiz-create': typeof AdminQuizCreateRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/students': typeof AdminStudentsRoute
  '/director/analytics': typeof DirectorAnalyticsRoute
  '/director/audit': typeof DirectorAuditRoute
  '/director/branches': typeof DirectorBranchesRoute
  '/director/courses': typeof DirectorCoursesRoute
  '/director/daily-report': typeof DirectorDailyReportRoute
  '/director/finance': typeof DirectorFinanceRoute
  '/director/integrations': typeof DirectorIntegrationsRoute
  '/director/leads': typeof DirectorLeadsRoute
  '/director/messages': typeof DirectorMessagesRoute
  '/director/notifications': typeof DirectorNotificationsRoute
  '/director/penalties': typeof DirectorPenaltiesRoute
  '/director/salaries': typeof DirectorSalariesRoute
  '/director/settings': typeof DirectorSettingsRoute
  '/director/staff': typeof DirectorStaffRoute
  '/director/students': typeof DirectorStudentsRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/profile': typeof ParentProfileRoute
  '/play/$code': typeof PlayCodeRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/superadmin/analytics': typeof SuperadminAnalyticsRoute
  '/superadmin/logs': typeof SuperadminLogsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/finance': typeof TeacherFinanceRoute
  '/teacher/grades': typeof TeacherGradesRoute
  '/teacher/groups': typeof TeacherGroupsRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/quiz-create': typeof TeacherQuizCreateRoute
  '/teacher/quizzes': typeof TeacherQuizzesRoute
  '/admin/': typeof AdminIndexRoute
  '/director/': typeof DirectorIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/quiz-session/$sessionId': typeof AdminQuizSessionSessionIdRoute
  '/teacher/quiz-session/$sessionId': typeof TeacherQuizSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/control': typeof AdminControlRoute
  '/admin/daily-report': typeof AdminDailyReportRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/quiz-create': typeof AdminQuizCreateRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/students': typeof AdminStudentsRoute
  '/director/analytics': typeof DirectorAnalyticsRoute
  '/director/audit': typeof DirectorAuditRoute
  '/director/branches': typeof DirectorBranchesRoute
  '/director/courses': typeof DirectorCoursesRoute
  '/director/daily-report': typeof DirectorDailyReportRoute
  '/director/finance': typeof DirectorFinanceRoute
  '/director/integrations': typeof DirectorIntegrationsRoute
  '/director/leads': typeof DirectorLeadsRoute
  '/director/messages': typeof DirectorMessagesRoute
  '/director/notifications': typeof DirectorNotificationsRoute
  '/director/penalties': typeof DirectorPenaltiesRoute
  '/director/salaries': typeof DirectorSalariesRoute
  '/director/settings': typeof DirectorSettingsRoute
  '/director/staff': typeof DirectorStaffRoute
  '/director/students': typeof DirectorStudentsRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/profile': typeof ParentProfileRoute
  '/play/$code': typeof PlayCodeRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/superadmin/analytics': typeof SuperadminAnalyticsRoute
  '/superadmin/logs': typeof SuperadminLogsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/finance': typeof TeacherFinanceRoute
  '/teacher/grades': typeof TeacherGradesRoute
  '/teacher/groups': typeof TeacherGroupsRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/quiz-create': typeof TeacherQuizCreateRoute
  '/teacher/quizzes': typeof TeacherQuizzesRoute
  '/admin': typeof AdminIndexRoute
  '/director': typeof DirectorIndexRoute
  '/parent': typeof ParentIndexRoute
  '/student': typeof StudentIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/quiz-session/$sessionId': typeof AdminQuizSessionSessionIdRoute
  '/teacher/quiz-session/$sessionId': typeof TeacherQuizSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/director': typeof DirectorRouteRouteWithChildren
  '/parent': typeof ParentRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/superadmin': typeof SuperadminRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/apply': typeof ApplyRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/control': typeof AdminControlRoute
  '/admin/daily-report': typeof AdminDailyReportRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/quiz-create': typeof AdminQuizCreateRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/students': typeof AdminStudentsRoute
  '/director/analytics': typeof DirectorAnalyticsRoute
  '/director/audit': typeof DirectorAuditRoute
  '/director/branches': typeof DirectorBranchesRoute
  '/director/courses': typeof DirectorCoursesRoute
  '/director/daily-report': typeof DirectorDailyReportRoute
  '/director/finance': typeof DirectorFinanceRoute
  '/director/integrations': typeof DirectorIntegrationsRoute
  '/director/leads': typeof DirectorLeadsRoute
  '/director/messages': typeof DirectorMessagesRoute
  '/director/notifications': typeof DirectorNotificationsRoute
  '/director/penalties': typeof DirectorPenaltiesRoute
  '/director/salaries': typeof DirectorSalariesRoute
  '/director/settings': typeof DirectorSettingsRoute
  '/director/staff': typeof DirectorStaffRoute
  '/director/students': typeof DirectorStudentsRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/profile': typeof ParentProfileRoute
  '/play/$code': typeof PlayCodeRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/superadmin/analytics': typeof SuperadminAnalyticsRoute
  '/superadmin/logs': typeof SuperadminLogsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/finance': typeof TeacherFinanceRoute
  '/teacher/grades': typeof TeacherGradesRoute
  '/teacher/groups': typeof TeacherGroupsRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/quiz-create': typeof TeacherQuizCreateRoute
  '/teacher/quizzes': typeof TeacherQuizzesRoute
  '/admin/': typeof AdminIndexRoute
  '/director/': typeof DirectorIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/quiz-session/$sessionId': typeof AdminQuizSessionSessionIdRoute
  '/teacher/quiz-session/$sessionId': typeof TeacherQuizSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/director'
    | '/parent'
    | '/student'
    | '/superadmin'
    | '/teacher'
    | '/apply'
    | '/join'
    | '/login'
    | '/admin/accounts'
    | '/admin/analytics'
    | '/admin/control'
    | '/admin/daily-report'
    | '/admin/finance'
    | '/admin/groups'
    | '/admin/leads'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/quiz-create'
    | '/admin/quizzes'
    | '/admin/schedule'
    | '/admin/students'
    | '/director/analytics'
    | '/director/audit'
    | '/director/branches'
    | '/director/courses'
    | '/director/daily-report'
    | '/director/finance'
    | '/director/integrations'
    | '/director/leads'
    | '/director/messages'
    | '/director/notifications'
    | '/director/penalties'
    | '/director/salaries'
    | '/director/settings'
    | '/director/staff'
    | '/director/students'
    | '/parent/children'
    | '/parent/messages'
    | '/parent/profile'
    | '/play/$code'
    | '/student/grades'
    | '/student/homework'
    | '/student/messages'
    | '/student/profile'
    | '/student/schedule'
    | '/superadmin/analytics'
    | '/superadmin/logs'
    | '/superadmin/settings'
    | '/teacher/attendance'
    | '/teacher/finance'
    | '/teacher/grades'
    | '/teacher/groups'
    | '/teacher/homework'
    | '/teacher/messages'
    | '/teacher/quiz-create'
    | '/teacher/quizzes'
    | '/admin/'
    | '/director/'
    | '/parent/'
    | '/student/'
    | '/superadmin/'
    | '/teacher/'
    | '/admin/quiz-session/$sessionId'
    | '/teacher/quiz-session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/join'
    | '/login'
    | '/admin/accounts'
    | '/admin/analytics'
    | '/admin/control'
    | '/admin/daily-report'
    | '/admin/finance'
    | '/admin/groups'
    | '/admin/leads'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/quiz-create'
    | '/admin/quizzes'
    | '/admin/schedule'
    | '/admin/students'
    | '/director/analytics'
    | '/director/audit'
    | '/director/branches'
    | '/director/courses'
    | '/director/daily-report'
    | '/director/finance'
    | '/director/integrations'
    | '/director/leads'
    | '/director/messages'
    | '/director/notifications'
    | '/director/penalties'
    | '/director/salaries'
    | '/director/settings'
    | '/director/staff'
    | '/director/students'
    | '/parent/children'
    | '/parent/messages'
    | '/parent/profile'
    | '/play/$code'
    | '/student/grades'
    | '/student/homework'
    | '/student/messages'
    | '/student/profile'
    | '/student/schedule'
    | '/superadmin/analytics'
    | '/superadmin/logs'
    | '/superadmin/settings'
    | '/teacher/attendance'
    | '/teacher/finance'
    | '/teacher/grades'
    | '/teacher/groups'
    | '/teacher/homework'
    | '/teacher/messages'
    | '/teacher/quiz-create'
    | '/teacher/quizzes'
    | '/admin'
    | '/director'
    | '/parent'
    | '/student'
    | '/superadmin'
    | '/teacher'
    | '/admin/quiz-session/$sessionId'
    | '/teacher/quiz-session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/director'
    | '/parent'
    | '/student'
    | '/superadmin'
    | '/teacher'
    | '/apply'
    | '/join'
    | '/login'
    | '/admin/accounts'
    | '/admin/analytics'
    | '/admin/control'
    | '/admin/daily-report'
    | '/admin/finance'
    | '/admin/groups'
    | '/admin/leads'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/quiz-create'
    | '/admin/quizzes'
    | '/admin/schedule'
    | '/admin/students'
    | '/director/analytics'
    | '/director/audit'
    | '/director/branches'
    | '/director/courses'
    | '/director/daily-report'
    | '/director/finance'
    | '/director/integrations'
    | '/director/leads'
    | '/director/messages'
    | '/director/notifications'
    | '/director/penalties'
    | '/director/salaries'
    | '/director/settings'
    | '/director/staff'
    | '/director/students'
    | '/parent/children'
    | '/parent/messages'
    | '/parent/profile'
    | '/play/$code'
    | '/student/grades'
    | '/student/homework'
    | '/student/messages'
    | '/student/profile'
    | '/student/schedule'
    | '/superadmin/analytics'
    | '/superadmin/logs'
    | '/superadmin/settings'
    | '/teacher/attendance'
    | '/teacher/finance'
    | '/teacher/grades'
    | '/teacher/groups'
    | '/teacher/homework'
    | '/teacher/messages'
    | '/teacher/quiz-create'
    | '/teacher/quizzes'
    | '/admin/'
    | '/director/'
    | '/parent/'
    | '/student/'
    | '/superadmin/'
    | '/teacher/'
    | '/admin/quiz-session/$sessionId'
    | '/teacher/quiz-session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DirectorRouteRoute: typeof DirectorRouteRouteWithChildren
  ParentRouteRoute: typeof ParentRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  SuperadminRouteRoute: typeof SuperadminRouteRouteWithChildren
  TeacherRouteRoute: typeof TeacherRouteRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  PlayCodeRoute: typeof PlayCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/director/': {
      id: '/director/'
      path: '/'
      fullPath: '/director/'
      preLoaderRoute: typeof DirectorIndexRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/teacher/quizzes': {
      id: '/teacher/quizzes'
      path: '/quizzes'
      fullPath: '/teacher/quizzes'
      preLoaderRoute: typeof TeacherQuizzesRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/quiz-create': {
      id: '/teacher/quiz-create'
      path: '/quiz-create'
      fullPath: '/teacher/quiz-create'
      preLoaderRoute: typeof TeacherQuizCreateRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/messages': {
      id: '/teacher/messages'
      path: '/messages'
      fullPath: '/teacher/messages'
      preLoaderRoute: typeof TeacherMessagesRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/homework': {
      id: '/teacher/homework'
      path: '/homework'
      fullPath: '/teacher/homework'
      preLoaderRoute: typeof TeacherHomeworkRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/groups': {
      id: '/teacher/groups'
      path: '/groups'
      fullPath: '/teacher/groups'
      preLoaderRoute: typeof TeacherGroupsRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/grades': {
      id: '/teacher/grades'
      path: '/grades'
      fullPath: '/teacher/grades'
      preLoaderRoute: typeof TeacherGradesRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/finance': {
      id: '/teacher/finance'
      path: '/finance'
      fullPath: '/teacher/finance'
      preLoaderRoute: typeof TeacherFinanceRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/superadmin/settings': {
      id: '/superadmin/settings'
      path: '/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof SuperadminSettingsRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/superadmin/logs': {
      id: '/superadmin/logs'
      path: '/logs'
      fullPath: '/superadmin/logs'
      preLoaderRoute: typeof SuperadminLogsRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/superadmin/analytics': {
      id: '/superadmin/analytics'
      path: '/analytics'
      fullPath: '/superadmin/analytics'
      preLoaderRoute: typeof SuperadminAnalyticsRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/student/schedule': {
      id: '/student/schedule'
      path: '/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof StudentScheduleRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/homework': {
      id: '/student/homework'
      path: '/homework'
      fullPath: '/student/homework'
      preLoaderRoute: typeof StudentHomeworkRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/grades': {
      id: '/student/grades'
      path: '/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof StudentGradesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/profile': {
      id: '/parent/profile'
      path: '/profile'
      fullPath: '/parent/profile'
      preLoaderRoute: typeof ParentProfileRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/messages': {
      id: '/parent/messages'
      path: '/messages'
      fullPath: '/parent/messages'
      preLoaderRoute: typeof ParentMessagesRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/parent/children': {
      id: '/parent/children'
      path: '/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof ParentChildrenRouteImport
      parentRoute: typeof ParentRouteRoute
    }
    '/director/students': {
      id: '/director/students'
      path: '/students'
      fullPath: '/director/students'
      preLoaderRoute: typeof DirectorStudentsRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/director/staff': {
      id: '/director/staff'
      path: '/staff'
      fullPath: '/director/staff'
      preLoaderRoute: typeof DirectorStaffRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/director/settings': {
      id: '/director/settings'
      path: '/settings'
      fullPath: '/director/settings'
      preLoaderRoute: typeof DirectorSettingsRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/director/salaries': {
      id: '/director/salaries'
      path: '/salaries'
      fullPath: '/director/salaries'
      preLoaderRoute: typeof DirectorSalariesRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/director/penalties': {
      id: '/director/penalties'
      path: '/penalties'
      fullPath: '/director/penalties'
      preLoaderRoute: typeof DirectorPenaltiesRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/director/notifications': {
      id: '/director/notifications'
      path: '/notifications'
      fullPath: '/director/notifications'
      preLoaderRoute: typeof DirectorNotificationsRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/director/messages': {
      id: '/director/messages'
      path: '/messages'
      fullPath: '/director/messages'
      preLoaderRoute: typeof DirectorMessagesRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/director/leads': {
      id: '/director/leads'
      path: '/leads'
      fullPath: '/director/leads'
      preLoaderRoute: typeof DirectorLeadsRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/director/integrations': {
      id: '/director/integrations'
      path: '/integrations'
      fullPath: '/director/integrations'
      preLoaderRoute: typeof DirectorIntegrationsRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/director/finance': {
      id: '/director/finance'
      path: '/finance'
      fullPath: '/director/finance'
      preLoaderRoute: typeof DirectorFinanceRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/director/daily-report': {
      id: '/director/daily-report'
      path: '/daily-report'
      fullPath: '/director/daily-report'
      preLoaderRoute: typeof DirectorDailyReportRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/director/courses': {
      id: '/director/courses'
      path: '/courses'
      fullPath: '/director/courses'
      preLoaderRoute: typeof DirectorCoursesRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/director/branches': {
      id: '/director/branches'
      path: '/branches'
      fullPath: '/director/branches'
      preLoaderRoute: typeof DirectorBranchesRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/director/audit': {
      id: '/director/audit'
      path: '/audit'
      fullPath: '/director/audit'
      preLoaderRoute: typeof DirectorAuditRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/director/analytics': {
      id: '/director/analytics'
      path: '/analytics'
      fullPath: '/director/analytics'
      preLoaderRoute: typeof DirectorAnalyticsRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/quizzes': {
      id: '/admin/quizzes'
      path: '/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AdminQuizzesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/quiz-create': {
      id: '/admin/quiz-create'
      path: '/quiz-create'
      fullPath: '/admin/quiz-create'
      preLoaderRoute: typeof AdminQuizCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/daily-report': {
      id: '/admin/daily-report'
      path: '/daily-report'
      fullPath: '/admin/daily-report'
      preLoaderRoute: typeof AdminDailyReportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/control': {
      id: '/admin/control'
      path: '/control'
      fullPath: '/admin/control'
      preLoaderRoute: typeof AdminControlRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/teacher/quiz-session/$sessionId': {
      id: '/teacher/quiz-session/$sessionId'
      path: '/quiz-session/$sessionId'
      fullPath: '/teacher/quiz-session/$sessionId'
      preLoaderRoute: typeof TeacherQuizSessionSessionIdRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/admin/quiz-session/$sessionId': {
      id: '/admin/quiz-session/$sessionId'
      path: '/quiz-session/$sessionId'
      fullPath: '/admin/quiz-session/$sessionId'
      preLoaderRoute: typeof AdminQuizSessionSessionIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminControlRoute: typeof AdminControlRoute
  AdminDailyReportRoute: typeof AdminDailyReportRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminQuizCreateRoute: typeof AdminQuizCreateRoute
  AdminQuizzesRoute: typeof AdminQuizzesRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminQuizSessionSessionIdRoute: typeof AdminQuizSessionSessionIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminControlRoute: AdminControlRoute,
  AdminDailyReportRoute: AdminDailyReportRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminQuizCreateRoute: AdminQuizCreateRoute,
  AdminQuizzesRoute: AdminQuizzesRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminQuizSessionSessionIdRoute: AdminQuizSessionSessionIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DirectorRouteRouteChildren {
  DirectorAnalyticsRoute: typeof DirectorAnalyticsRoute
  DirectorAuditRoute: typeof DirectorAuditRoute
  DirectorBranchesRoute: typeof DirectorBranchesRoute
  DirectorCoursesRoute: typeof DirectorCoursesRoute
  DirectorDailyReportRoute: typeof DirectorDailyReportRoute
  DirectorFinanceRoute: typeof DirectorFinanceRoute
  DirectorIntegrationsRoute: typeof DirectorIntegrationsRoute
  DirectorLeadsRoute: typeof DirectorLeadsRoute
  DirectorMessagesRoute: typeof DirectorMessagesRoute
  DirectorNotificationsRoute: typeof DirectorNotificationsRoute
  DirectorPenaltiesRoute: typeof DirectorPenaltiesRoute
  DirectorSalariesRoute: typeof DirectorSalariesRoute
  DirectorSettingsRoute: typeof DirectorSettingsRoute
  DirectorStaffRoute: typeof DirectorStaffRoute
  DirectorStudentsRoute: typeof DirectorStudentsRoute
  DirectorIndexRoute: typeof DirectorIndexRoute
}

const DirectorRouteRouteChildren: DirectorRouteRouteChildren = {
  DirectorAnalyticsRoute: DirectorAnalyticsRoute,
  DirectorAuditRoute: DirectorAuditRoute,
  DirectorBranchesRoute: DirectorBranchesRoute,
  DirectorCoursesRoute: DirectorCoursesRoute,
  DirectorDailyReportRoute: DirectorDailyReportRoute,
  DirectorFinanceRoute: DirectorFinanceRoute,
  DirectorIntegrationsRoute: DirectorIntegrationsRoute,
  DirectorLeadsRoute: DirectorLeadsRoute,
  DirectorMessagesRoute: DirectorMessagesRoute,
  DirectorNotificationsRoute: DirectorNotificationsRoute,
  DirectorPenaltiesRoute: DirectorPenaltiesRoute,
  DirectorSalariesRoute: DirectorSalariesRoute,
  DirectorSettingsRoute: DirectorSettingsRoute,
  DirectorStaffRoute: DirectorStaffRoute,
  DirectorStudentsRoute: DirectorStudentsRoute,
  DirectorIndexRoute: DirectorIndexRoute,
}

const DirectorRouteRouteWithChildren = DirectorRouteRoute._addFileChildren(
  DirectorRouteRouteChildren,
)

interface ParentRouteRouteChildren {
  ParentChildrenRoute: typeof ParentChildrenRoute
  ParentMessagesRoute: typeof ParentMessagesRoute
  ParentProfileRoute: typeof ParentProfileRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteRouteChildren: ParentRouteRouteChildren = {
  ParentChildrenRoute: ParentChildrenRoute,
  ParentMessagesRoute: ParentMessagesRoute,
  ParentProfileRoute: ParentProfileRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteRouteWithChildren = ParentRouteRoute._addFileChildren(
  ParentRouteRouteChildren,
)

interface StudentRouteRouteChildren {
  StudentGradesRoute: typeof StudentGradesRoute
  StudentHomeworkRoute: typeof StudentHomeworkRoute
  StudentMessagesRoute: typeof StudentMessagesRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentScheduleRoute: typeof StudentScheduleRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentGradesRoute: StudentGradesRoute,
  StudentHomeworkRoute: StudentHomeworkRoute,
  StudentMessagesRoute: StudentMessagesRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentScheduleRoute: StudentScheduleRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

interface SuperadminRouteRouteChildren {
  SuperadminAnalyticsRoute: typeof SuperadminAnalyticsRoute
  SuperadminLogsRoute: typeof SuperadminLogsRoute
  SuperadminSettingsRoute: typeof SuperadminSettingsRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteRouteChildren: SuperadminRouteRouteChildren = {
  SuperadminAnalyticsRoute: SuperadminAnalyticsRoute,
  SuperadminLogsRoute: SuperadminLogsRoute,
  SuperadminSettingsRoute: SuperadminSettingsRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteRouteWithChildren = SuperadminRouteRoute._addFileChildren(
  SuperadminRouteRouteChildren,
)

interface TeacherRouteRouteChildren {
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherFinanceRoute: typeof TeacherFinanceRoute
  TeacherGradesRoute: typeof TeacherGradesRoute
  TeacherGroupsRoute: typeof TeacherGroupsRoute
  TeacherHomeworkRoute: typeof TeacherHomeworkRoute
  TeacherMessagesRoute: typeof TeacherMessagesRoute
  TeacherQuizCreateRoute: typeof TeacherQuizCreateRoute
  TeacherQuizzesRoute: typeof TeacherQuizzesRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherQuizSessionSessionIdRoute: typeof TeacherQuizSessionSessionIdRoute
}

const TeacherRouteRouteChildren: TeacherRouteRouteChildren = {
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherFinanceRoute: TeacherFinanceRoute,
  TeacherGradesRoute: TeacherGradesRoute,
  TeacherGroupsRoute: TeacherGroupsRoute,
  TeacherHomeworkRoute: TeacherHomeworkRoute,
  TeacherMessagesRoute: TeacherMessagesRoute,
  TeacherQuizCreateRoute: TeacherQuizCreateRoute,
  TeacherQuizzesRoute: TeacherQuizzesRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherQuizSessionSessionIdRoute: TeacherQuizSessionSessionIdRoute,
}

const TeacherRouteRouteWithChildren = TeacherRouteRoute._addFileChildren(
  TeacherRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DirectorRouteRoute: DirectorRouteRouteWithChildren,
  ParentRouteRoute: ParentRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  SuperadminRouteRoute: SuperadminRouteRouteWithChildren,
  TeacherRouteRoute: TeacherRouteRouteWithChildren,
  ApplyRoute: ApplyRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  PlayCodeRoute: PlayCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
