# Generated by Django 6.0.4 on 2026-06-11 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_studentlead_trial_lesson_attended_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_uz', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200)),
                ('description_uz', models.CharField(blank=True, max_length=500)),
                ('description_ru', models.CharField(blank=True, max_length=500)),
                ('icon', models.CharField(default='trophy', max_length=50)),
                ('condition_type', models.CharField(choices=[('streak', 'Streak days'), ('total_coins', 'Total coins earned'), ('attendance', 'Attendance count'), ('grade_count', 'Perfect grades count'), ('homework', 'Homework submitted'), ('quiz_wins', 'Quiz wins'), ('level', 'Reach level')], max_length=30)),
                ('condition_value', models.PositiveIntegerField()),
                ('reward_coins', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coins_achievement',
            },
        ),
        migrations.CreateModel(
            name='CoinSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_present', models.PositiveIntegerField(default=10)),
                ('coins_late', models.PositiveIntegerField(default=5)),
                ('coins_grade_perfect', models.PositiveIntegerField(default=20)),
                ('coins_grade_good', models.PositiveIntegerField(default=10)),
                ('coins_homework_done', models.PositiveIntegerField(default=15)),
                ('coins_quiz_correct', models.PositiveIntegerField(default=5)),
                ('coins_streak_7', models.PositiveIntegerField(default=50)),
                ('coins_streak_30', models.PositiveIntegerField(default=200)),
                ('xp_per_coin', models.PositiveIntegerField(default=3)),
                ('level_thresholds', models.JSONField(default=list)),
                ('store_open_days', models.JSONField(default=list)),
                ('max_purchases_per_week', models.PositiveIntegerField(default=1)),
                ('max_purchases_per_month', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coins_setting',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uz', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('price_coins', models.PositiveIntegerField()),
                ('stock', models.IntegerField(default=-1)),
                ('min_level', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coins_product',
                'ordering': ['category', 'price_coins'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uz', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'coins_product_category',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoinWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coin_wallet', to='students.student')),
            ],
            options={
                'db_table': 'coins_wallet',
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earn', 'Earn'), ('spend', 'Spend'), ('adjustment', 'Adjustment'), ('penalty', 'Penalty')], max_length=20)),
                ('reason', models.CharField(choices=[('attendance', 'Attendance'), ('grade', 'Grade'), ('homework', 'Homework'), ('quiz', 'Quiz'), ('streak', 'Streak'), ('purchase', 'Purchase'), ('manual', 'Manual'), ('penalty', 'Penalty')], max_length=20)),
                ('amount', models.IntegerField()),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('balance_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='coins.coinwallet')),
            ],
            options={
                'db_table': 'coins_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('coins_spent', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='coins.coinwallet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='coins.product')),
            ],
            options={
                'db_table': 'coins_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='coins.productcategory'),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.achievement')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='coins.coinwallet')),
            ],
            options={
                'db_table': 'coins_user_achievement',
                'unique_together': {('wallet', 'achievement')},
            },
        ),
    ]
