# Generated by Django 6.0.4 on 2026-06-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinsetting',
            name='coins_absent_penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coinsetting',
            name='coins_late_penalty',
            field=models.IntegerField(default=0),
        ),
    ]
