# Generated by Django 5.1.15 on 2026-04-25 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('online', 'Online')], max_length=20)),
                ('late_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('is_charged', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='lessons.lesson')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='students.student')),
            ],
            options={
                'db_table': 'lessons_attendance',
                'indexes': [models.Index(fields=['student', 'lesson'], name='lessons_att_student_87e8a7_idx'), models.Index(fields=['status'], name='lessons_att_status_cca8b6_idx')],
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
