# Generated by Django 6.0.4 on 2026-06-10 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_teacherattendance'),
        ('staff', '0005_supportteacherlink'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_attendances', to='staff.staff'),
        ),
        migrations.AddConstraint(
            model_name='teacherattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('teacher__isnull', False)), fields=('lesson', 'teacher'), name='unique_teacher_attendance_per_lesson'),
        ),
    ]
